/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.ofsouzap.distributedsystemsim;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void sanityTest() { }
}
