/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.ofsouzap.distributedsystemsim;

import org.junit.jupiter.api.Test;

import com.github.ofsouzap.distributedsystemsim.simulation.Simulator;
import com.github.ofsouzap.distributedsystemsim.simulation.logging.NullLogger;
import com.github.ofsouzap.distributedsystemsim.simulation.network.Network;

import static org.junit.jupiter.api.Assertions.*;

class SimulatorTest {
    @Test void stepWorks() {
        // Network net = new Netwo
        Simulator sim = new Simulator(new NullLogger(), null);
    }
}
