/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.ofsouzap.distributedsystemsim;

import org.junit.jupiter.api.Test;

import com.github.ofsouzap.distributedsystemsim.simulation.Simulator;
import com.github.ofsouzap.distributedsystemsim.simulation.logging.NullLogger;
import com.github.ofsouzap.distributedsystemsim.simulation.network.Network;
import com.github.ofsouzap.distributedsystemsim.simulation.network.ReliableSynchronousNetwork;

class SimulatorTest {
    @Test void simulatorStep() {
        Network net = new ReliableSynchronousNetwork();
        Simulator sim = new Simulator(new NullLogger(), net);
        sim.step();
    }
}
