/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package distributed.system.sim;

import distributed.system.sim.examples.basicExample.StringMessage;
import distributed.system.sim.examples.basicExample.network.BasicNetwork;
import distributed.system.sim.examples.basicExample.nodes.NullNode;
import distributed.system.sim.examples.basicExample.nodes.TimedBroadcastNode;
import distributed.system.sim.simulation.SimulationController;
import distributed.system.sim.simulation.Simulator;
import distributed.system.sim.simulation.logging.ConsoleLogger;
import distributed.system.sim.simulation.logging.EventLogger;
import distributed.system.sim.simulation.network.Network;

public class App {
    public static void main(String[] args) {
        final int N = 10;

        // Create logger
        EventLogger logger = new ConsoleLogger();

        // Create network
        Network network = new BasicNetwork();
        network.addNode(new TimedBroadcastNode(1, new StringMessage("message1")));
        network.addNode(new TimedBroadcastNode(5, new StringMessage("message2")));
        network.addNode(new NullNode());

        // Create simulator
        SimulationController simulator = new Simulator(logger, network);

        // Simulate
        for (int i = 0; i < N; i++){
            simulator.step();
        }
    }
}
