/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.ofsouzap.distributedsystemsim.examples;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        try (Scanner scanner = new Scanner(System.in)) {
            Scanning.scanner = scanner;

            // ExampleApp basicExample = new com.github.ofsouzap.distributedsystemsim.examples.basicExample.App();
            ExampleApp shardedReadonlyDatabase = new com.github.ofsouzap.distributedsystemsim.examples.shardedReadonlyDatabase.App();

            // TODO - use args to select which to run

            // basicExample.run(args);
            shardedReadonlyDatabase.run(args);
        }
    }
}
